# Generated by Django 4.2.2 on 2023-07-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_alter_advertisements_auction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
