# Generated by Django 4.2.2 on 2023-07-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_alter_advertisements_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'verbose_name': 'Объявление'},
        ),
    ]
