# Generated by Django 4.2.2 on 2023-08-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0008_alter_advertisements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='..static/img/adv.png', upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
